namespace CodeOrbit.Core.Sources;

/// <summary>
/// Hook installation strategy for Cline per-event PowerShell scripts.
/// Format: one generated script per event in the configured hooks directory.
/// </summary>
internal sealed class ClineHookStrategy : IHookInstallationStrategy
{
    private const string GeneratedMarker = "Auto-generated by CodeOrbit";

    public bool Install(string sourceKey, HookInstallationSpec spec)
    {
        try
        {
            var hooksDirectory = ResolveHooksDirectory(spec.ConfigPath);
            Directory.CreateDirectory(hooksDirectory);

            var command = ToPowerShellInvocation(HookInstallationUtils.GetHookCommand(sourceKey));
            foreach (var eventName in spec.Events)
            {
                File.WriteAllText(GetEventScriptPath(hooksDirectory, eventName), $"""
                    # {GeneratedMarker}
                    {command}
                    """);
            }

            return true;
        }
        catch
        {
            return false;
        }
    }

    public bool Uninstall(string sourceKey, HookInstallationSpec spec)
    {
        try
        {
            var hooksDirectory = ResolveHooksDirectory(spec.ConfigPath);
            if (!Directory.Exists(hooksDirectory))
                return true;

            foreach (var eventName in spec.Events)
            {
                var scriptPath = GetEventScriptPath(hooksDirectory, eventName);
                if (!File.Exists(scriptPath))
                    continue;

                var content = File.ReadAllText(scriptPath);
                if (IsGeneratedCodeOrbitScript(content, sourceKey))
                    File.Delete(scriptPath);
            }

            if (Directory.GetFileSystemEntries(hooksDirectory).Length == 0)
                Directory.Delete(hooksDirectory);

            return true;
        }
        catch
        {
            return false;
        }
    }

    public bool IsInstalled(string sourceKey, HookInstallationSpec spec)
    {
        try
        {
            var hooksDirectory = ResolveHooksDirectory(spec.ConfigPath);
            if (!Directory.Exists(hooksDirectory))
                return false;

            return spec.Events
                .Select(eventName => GetEventScriptPath(hooksDirectory, eventName))
                .Any(scriptPath =>
                    File.Exists(scriptPath) &&
                    IsGeneratedCodeOrbitScript(File.ReadAllText(scriptPath), sourceKey));
        }
        catch
        {
            return false;
        }
    }

    private static string ResolveHooksDirectory(string configPath)
    {
        var expandedPath = HookInstallationUtils.ExpandPath(configPath);
        return Path.HasExtension(expandedPath)
            ? Path.GetDirectoryName(expandedPath) ?? expandedPath
            : expandedPath;
    }

    private static string GetEventScriptPath(string hooksDirectory, string eventName) =>
        Path.Combine(hooksDirectory, $"{eventName}.ps1");

    private static string ToPowerShellInvocation(string command) =>
        command.TrimStart().StartsWith('"') ? $"& {command}" : command;

    private static bool IsGeneratedCodeOrbitScript(string content, string sourceKey) =>
        content.Contains(GeneratedMarker, StringComparison.OrdinalIgnoreCase) &&
        (content.Contains("CodeOrbit.Bridge", StringComparison.OrdinalIgnoreCase) ||
         content.Contains("CodeOrbit-bridge", StringComparison.OrdinalIgnoreCase) ||
         content.Contains($"--source {sourceKey}", StringComparison.OrdinalIgnoreCase));
}
