using System.Text.Json.Nodes;
using CodeOrbit.Core.Sources;
using Xunit;

namespace CodeOrbit.Core.Tests;

public sealed class HookInstallationStrategyTests : IDisposable
{
    private readonly string _tempDir;

    public HookInstallationStrategyTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"CodeOrbit-hook-strategy-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_tempDir))
                Directory.Delete(_tempDir, true);
        }
        catch
        {
            // Ignore cleanup failures in tests.
        }
    }

    [Theory]
    [InlineData(HookFormats.Copilot)]
    [InlineData(HookFormats.Cline)]
    public void HookStrategyFactory_CreatesNewPluginFormats(string format)
    {
        Assert.True(HookFormats.IsSupported(format));
        Assert.NotNull(HookStrategyFactory.Create(format));
    }

    [Fact]
    public void CopilotStrategy_InstallsIdempotentlyAndPreservesUserHooks()
    {
        var hooksPath = Path.Combine(_tempDir, ".copilot", "hooks", "hooks.json");
        Directory.CreateDirectory(Path.GetDirectoryName(hooksPath)!);
        File.WriteAllText(hooksPath, """
            {
              "version": 1,
              "hooks": [
                {
                  "event": "CustomEvent",
                  "command": "user-command",
                  "timeout": 30
                }
              ]
            }
            """);

        var spec = new HookInstallationSpec(
            HookFormats.Copilot,
            hooksPath,
            ["PreToolUse", "PostToolUse"],
            10,
            ExtraConfig: null);
        var strategy = Assert.IsType<CopilotHookStrategy>(HookStrategyFactory.Create(HookFormats.Copilot));

        Assert.True(strategy.Install("copilot", spec));
        Assert.True(strategy.Install("copilot", spec));
        Assert.True(strategy.IsInstalled("copilot", spec));

        var root = Assert.IsType<JsonObject>(JsonNode.Parse(File.ReadAllText(hooksPath)));
        var hooks = Assert.IsType<JsonArray>(root["hooks"]);

        Assert.Contains(hooks, hook => hook?["command"]?.GetValue<string>() == "user-command");
        Assert.Equal(1, hooks.Count(hook => hook?["event"]?.GetValue<string>() == "PreToolUse"));
        Assert.Equal(1, hooks.Count(hook => hook?["event"]?.GetValue<string>() == "PostToolUse"));

        Assert.True(strategy.Uninstall("copilot", spec));
        Assert.False(strategy.IsInstalled("copilot", spec));

        root = Assert.IsType<JsonObject>(JsonNode.Parse(File.ReadAllText(hooksPath)));
        hooks = Assert.IsType<JsonArray>(root["hooks"]);
        Assert.Single(hooks);
        Assert.Equal("user-command", hooks[0]?["command"]?.GetValue<string>());
    }

    [Fact]
    public void ClineStrategy_InstallsPerEventScriptsAndRemovesOnlyGeneratedFiles()
    {
        var hooksDir = Path.Combine(_tempDir, "Documents", "Cline", "Hooks");
        Directory.CreateDirectory(hooksDir);
        var userScript = Path.Combine(hooksDir, "Custom.ps1");
        File.WriteAllText(userScript, "Write-Host user");

        var spec = new HookInstallationSpec(
            HookFormats.Cline,
            hooksDir,
            ["SessionStart", "PreToolUse"],
            10,
            ExtraConfig: null);
        var strategy = Assert.IsType<ClineHookStrategy>(HookStrategyFactory.Create(HookFormats.Cline));

        Assert.True(strategy.Install("cline", spec));
        Assert.True(strategy.IsInstalled("cline", spec));

        var preToolUseScript = Path.Combine(hooksDir, "PreToolUse.ps1");
        Assert.True(File.Exists(preToolUseScript));
        var content = File.ReadAllText(preToolUseScript);
        Assert.Contains("Auto-generated by CodeOrbit", content);
        Assert.Contains("--source cline", content);
        var commandLine = content
            .Replace("\r\n", "\n")
            .Split('\n')
            .Last(line => !string.IsNullOrWhiteSpace(line))
            .Trim();
        Assert.StartsWith("& ", commandLine);

        Assert.True(strategy.Uninstall("cline", spec));
        Assert.False(strategy.IsInstalled("cline", spec));
        Assert.False(File.Exists(preToolUseScript));
        Assert.True(File.Exists(userScript));
    }
}
